<%@  Title="Upravljanje z knjigami" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="KnjigeNaVoljo.aspx.cs" Inherits="KnjigeNaVoljo" %>

<asp:Content runat="server" ContentPlaceHolderID="MainContent">
    <!DOCTYPE html>

    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Upravljanje z knjigami</title>

        <webopt:BundleReference runat="server" Path="~/Content/css" />

        <link rel="stylesheet" type="text/css" href="stili.css" />
        <style type="text/css">
            .auto-style4 {
                width: 829px;
            }

            .auto-style5 {
                width: 41px;
            }

            .auto-style6 {
                width: 647px;
            }

            .auto-style7 {
                height: 546px;
                width: 1170px;
                text-align: center;
                margin-left: auto;
                margin-right: auto;
                margin-top: 0px;
                padding-left: 15px;
                padding-right: 15px;
            }
        </style>
    </head>
    <body>

        <asp:Label ID="Message"
            ForeColor="Red"
            runat="server" />
        <h1 style="text-align: center;">Upravljanje z knjigami</h1>
        <hr style="width: 900px;" />
        <%-- GridView Knjig ki so trenutno na voljo --%>
        <div style="margin-top: 50px; text-align: center; width: 800px; margin: 35px auto;" draggable="true">
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="ID" DataSourceID="Knjige" Height="230px" Width="750px" CssClass="auto-style1" HorizontalAlign="Justify"
                AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" AllowPaging="True" PageSize="7">
                <HeaderStyle Height="35px" HorizontalAlign="Center" />
                <PagerSettings FirstPageText="&amp;lt; &amp;lt;" />
                <RowStyle Height="25px" HorizontalAlign="Center" VerticalAlign="NotSet" />
                <Columns>
                    <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="ID" />
                    <asp:BoundField DataField="NaslovKnjige" HeaderText="NaslovKnjige" SortExpression="NaslovKnjige" />
                    <asp:BoundField DataField="Pisatelj" HeaderText="Pisatelj" SortExpression="Pisatelj" />
                    <asp:BoundField DataField="LetoIzdaje" HeaderText="LetoIzdaje" SortExpression="LetoIzdaje" />
                    <asp:BoundField DataField="NaVoljo" HeaderText="NaVoljo" SortExpression="NaVoljo" />
                </Columns>
            </asp:GridView>
            <asp:SqlDataSource ID="Knjige" runat="server" ConnectionString="<%$ ConnectionStrings:myConnectionString %>"
                SelectCommand="SELECT * FROM [Knjige]"
                DeleteCommand="DELETE FROM Knjige WHERE ID = @ID"
                UpdateCommand="UPDATE Knjige SET NaslovKnjige=@NaslovKnjige, Pisatelj=@Pisatelj, LetoIzdaje=@LetoIzdaje, NaVoljo=@NaVoljo WHERE ID=@ID"></asp:SqlDataSource>

            <%--DODAJANJE KNJIGE--%>
            <table border="0" style="border-collapse: collapse; margin-top: 20px; width: 750px;" class="auto-style6">
                <tr>
                    <td style="width: 150px">Naslov knjige:<br />
                        <asp:TextBox ID="naslovKnjige" runat="server" Width="140" />
                    </td>
                    <td style="width: 150px">Pisatelj:<br />
                        <asp:TextBox ID="pisatelj" runat="server" Width="140" />
                    </td>
                    <td style="width: 150px">Leto izdaje:<br />
                        <asp:TextBox ID="letoIzdaje" runat="server" Width="140" />
                        <td style="width: 150px">Na voljo:<br />
                            <asp:TextBox ID="naVoljo" runat="server" Width="140" />
                        </td>
                    </td>
                    <td class="auto-style5">
                        <asp:Button ID="btnAdd" runat="server" Text="Dodaj" OnClick="GridView1_Add" />
                    </td>
                </tr>

            </table>
        </div>
        <div class="auto-style7">
        </div>
    </body>
    </html>
</asp:Content>

